title: Quantum Service-oriented Computing - A Practical Introduction to Quantum Web Services and Quantum Workflows
description: ICSOFT 2026 Tutorial
theme: jekyll-theme-cayman
baseurl: /icsoft-2026-tutorial
url: http://LaviniaStiliadou.github.io
